In [1]:
import tensorflow as tf
import numpy as np

In [3]:
xy = np.loadtxt('data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
print(x_data.shape)
print(y_data.shape)

(101, 16)
(101, 1)


In [5]:
nb_classes = 7

In [6]:
# y_data를 원핫인코딩으로 변환하기
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [7]:
tf.model = tf.keras.Sequential()

In [8]:
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=x_data.shape[1], activation='softmax'))

In [9]:
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.01), metrics=['accuracy'])

In [10]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


In [11]:
history = tf.model.fit(x_data, y_one_hot, epochs=1000)

Train on 101 samples
Epoch 1/1000
101/101 [==============================] - 3s 28ms/sample - loss: 1.9867 - accuracy: 0.2475
Epoch 2/1000
101/101 [==============================] - 0s 360us/sample - loss: 1.9152 - accuracy: 0.2970
Epoch 3/1000
101/101 [==============================] - 0s 543us/sample - loss: 1.8513 - accuracy: 0.3663
Epoch 4/1000
101/101 [==============================] - 0s 444us/sample - loss: 1.8028 - accuracy: 0.3861
Epoch 5/1000
101/101 [==============================] - 0s 498us/sample - loss: 1.7616 - accuracy: 0.3960
Epoch 6/1000
101/101 [==============================] - 0s 553us/sample - loss: 1.7217 - accuracy: 0.4158
Epoch 7/1000
101/101 [==============================] - 0s 553us/sample - loss: 1.6894 - accuracy: 0.4455
Epoch 8/1000
101/101 [==============================] - 0s 484us/sample - loss: 1.6577 - accuracy: 0.4653
Epoch 9/1000
101/101 [==============================] - 0s 573us/sample - loss: 1.6245 - accuracy: 0.4752
Epoch 10/1000
101/101 [===

101/101 [==============================] - 0s 344us/sample - loss: 0.8663 - accuracy: 0.7921
Epoch 77/1000
101/101 [==============================] - 0s 311us/sample - loss: 0.8604 - accuracy: 0.7921
Epoch 78/1000
101/101 [==============================] - 0s 306us/sample - loss: 0.8553 - accuracy: 0.8020
Epoch 79/1000
101/101 [==============================] - 0s 311us/sample - loss: 0.8505 - accuracy: 0.8020
Epoch 80/1000
101/101 [==============================] - 0s 296us/sample - loss: 0.8451 - accuracy: 0.8218
Epoch 81/1000
101/101 [==============================] - ETA: 0s - loss: 0.9022 - accuracy: 0.78 - 0s 365us/sample - loss: 0.8404 - accuracy: 0.8218
Epoch 82/1000
101/101 [==============================] - 0s 395us/sample - loss: 0.8358 - accuracy: 0.8119
Epoch 83/1000
101/101 [==============================] - 0s 484us/sample - loss: 0.8305 - accuracy: 0.8416
Epoch 84/1000
101/101 [==============================] - 0s 533us/sample - loss: 0.8263 - accuracy: 0.8416
Epoch 85/

101/101 [==============================] - 0s 276us/sample - loss: 0.6199 - accuracy: 0.8713
Epoch 149/1000
101/101 [==============================] - 0s 257us/sample - loss: 0.6176 - accuracy: 0.8713
Epoch 150/1000
101/101 [==============================] - 0s 267us/sample - loss: 0.6155 - accuracy: 0.8713
Epoch 151/1000
101/101 [==============================] - 0s 247us/sample - loss: 0.6131 - accuracy: 0.8713
Epoch 152/1000
101/101 [==============================] - 0s 247us/sample - loss: 0.6117 - accuracy: 0.8713
Epoch 153/1000
101/101 [==============================] - 0s 247us/sample - loss: 0.6094 - accuracy: 0.8713
Epoch 154/1000
101/101 [==============================] - 0s 257us/sample - loss: 0.6072 - accuracy: 0.8713
Epoch 155/1000
101/101 [==============================] - 0s 247us/sample - loss: 0.6053 - accuracy: 0.8713
Epoch 156/1000
101/101 [==============================] - 0s 247us/sample - loss: 0.6038 - accuracy: 0.8713
Epoch 157/1000
101/101 [===================

101/101 [==============================] - 0s 272us/sample - loss: 0.4994 - accuracy: 0.9010
Epoch 224/1000
101/101 [==============================] - 0s 375us/sample - loss: 0.4980 - accuracy: 0.9010
Epoch 225/1000
101/101 [==============================] - 0s 316us/sample - loss: 0.4968 - accuracy: 0.9010
Epoch 226/1000
101/101 [==============================] - 0s 316us/sample - loss: 0.4962 - accuracy: 0.9010
Epoch 227/1000
101/101 [==============================] - 0s 286us/sample - loss: 0.4946 - accuracy: 0.9010
Epoch 228/1000
101/101 [==============================] - 0s 292us/sample - loss: 0.4932 - accuracy: 0.9010
Epoch 229/1000
101/101 [==============================] - 0s 316us/sample - loss: 0.4926 - accuracy: 0.9010
Epoch 230/1000
101/101 [==============================] - 0s 326us/sample - loss: 0.4914 - accuracy: 0.9010
Epoch 231/1000
101/101 [==============================] - 0s 355us/sample - loss: 0.4900 - accuracy: 0.9010
Epoch 232/1000
101/101 [===================

Epoch 299/1000
101/101 [==============================] - ETA: 0s - loss: 0.3295 - accuracy: 1.00 - 0s 573us/sample - loss: 0.4269 - accuracy: 0.9208
Epoch 300/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.4262 - accuracy: 0.9208
Epoch 301/1000
101/101 [==============================] - 0s 355us/sample - loss: 0.4255 - accuracy: 0.9208
Epoch 302/1000
101/101 [==============================] - 0s 425us/sample - loss: 0.4251 - accuracy: 0.9208
Epoch 303/1000
101/101 [==============================] - 0s 425us/sample - loss: 0.4241 - accuracy: 0.9208
Epoch 304/1000
101/101 [==============================] - 0s 592us/sample - loss: 0.4232 - accuracy: 0.9208
Epoch 305/1000
101/101 [==============================] - 0s 598us/sample - loss: 0.4224 - accuracy: 0.9208
Epoch 306/1000
101/101 [==============================] - 0s 681us/sample - loss: 0.4215 - accuracy: 0.9208
Epoch 307/1000
101/101 [==============================] - 0s 701us/sample - loss: 0.4205 - acc

101/101 [==============================] - 0s 453us/sample - loss: 0.3770 - accuracy: 0.9406
Epoch 374/1000
101/101 [==============================] - 0s 346us/sample - loss: 0.3765 - accuracy: 0.9406
Epoch 375/1000
101/101 [==============================] - 0s 374us/sample - loss: 0.3761 - accuracy: 0.9406
Epoch 376/1000
101/101 [==============================] - 0s 444us/sample - loss: 0.3754 - accuracy: 0.9406
Epoch 377/1000
101/101 [==============================] - 0s 510us/sample - loss: 0.3746 - accuracy: 0.9406
Epoch 378/1000
101/101 [==============================] - 0s 642us/sample - loss: 0.3742 - accuracy: 0.9406
Epoch 379/1000
101/101 [==============================] - 0s 553us/sample - loss: 0.3737 - accuracy: 0.9406
Epoch 380/1000
101/101 [==============================] - 0s 584us/sample - loss: 0.3731 - accuracy: 0.9406
Epoch 381/1000
101/101 [==============================] - 0s 667us/sample - loss: 0.3725 - accuracy: 0.9406
Epoch 382/1000
101/101 [===================

101/101 [==============================] - 0s 593us/sample - loss: 0.3402 - accuracy: 0.9406
Epoch 448/1000
101/101 [==============================] - 0s 464us/sample - loss: 0.3395 - accuracy: 0.9406
Epoch 449/1000
101/101 [==============================] - 0s 494us/sample - loss: 0.3390 - accuracy: 0.9406
Epoch 450/1000
101/101 [==============================] - 0s 993us/sample - loss: 0.3388 - accuracy: 0.9406
Epoch 451/1000
101/101 [==============================] - 0s 523us/sample - loss: 0.3382 - accuracy: 0.9406
Epoch 452/1000
101/101 [==============================] - 0s 662us/sample - loss: 0.3380 - accuracy: 0.9406
Epoch 453/1000
101/101 [==============================] - 0s 459us/sample - loss: 0.3375 - accuracy: 0.9406
Epoch 454/1000
101/101 [==============================] - 0s 523us/sample - loss: 0.3373 - accuracy: 0.9406
Epoch 455/1000
101/101 [==============================] - 0s 627us/sample - loss: 0.3367 - accuracy: 0.9406
Epoch 456/1000
101/101 [===================

101/101 [==============================] - 0s 484us/sample - loss: 0.3110 - accuracy: 0.9406
Epoch 523/1000
101/101 [==============================] - 0s 523us/sample - loss: 0.3108 - accuracy: 0.9406
Epoch 524/1000
101/101 [==============================] - 0s 523us/sample - loss: 0.3103 - accuracy: 0.9406
Epoch 525/1000
101/101 [==============================] - 0s 424us/sample - loss: 0.3100 - accuracy: 0.9406
Epoch 526/1000
101/101 [==============================] - 0s 533us/sample - loss: 0.3096 - accuracy: 0.9406
Epoch 527/1000
101/101 [==============================] - 0s 583us/sample - loss: 0.3094 - accuracy: 0.9406
Epoch 528/1000
101/101 [==============================] - 0s 573us/sample - loss: 0.3090 - accuracy: 0.9406
Epoch 529/1000
101/101 [==============================] - 0s 721us/sample - loss: 0.3086 - accuracy: 0.9406
Epoch 530/1000
101/101 [==============================] - 0s 652us/sample - loss: 0.3082 - accuracy: 0.9406
Epoch 531/1000
101/101 [===================

101/101 [==============================] - 0s 395us/sample - loss: 0.2868 - accuracy: 0.9505
Epoch 598/1000
101/101 [==============================] - 0s 505us/sample - loss: 0.2866 - accuracy: 0.9505
Epoch 599/1000
101/101 [==============================] - 0s 404us/sample - loss: 0.2861 - accuracy: 0.9505
Epoch 600/1000
101/101 [==============================] - 0s 474us/sample - loss: 0.2859 - accuracy: 0.9505
Epoch 601/1000
101/101 [==============================] - 0s 456us/sample - loss: 0.2855 - accuracy: 0.9505
Epoch 602/1000
101/101 [==============================] - 0s 504us/sample - loss: 0.2853 - accuracy: 0.9505
Epoch 603/1000
101/101 [==============================] - 0s 627us/sample - loss: 0.2848 - accuracy: 0.9505
Epoch 604/1000
101/101 [==============================] - 0s 375us/sample - loss: 0.2846 - accuracy: 0.9505
Epoch 605/1000
101/101 [==============================] - 0s 434us/sample - loss: 0.2845 - accuracy: 0.9505
Epoch 606/1000
101/101 [===================

Epoch 673/1000
101/101 [==============================] - 0s 385us/sample - loss: 0.2655 - accuracy: 0.9604
Epoch 674/1000
101/101 [==============================] - 0s 366us/sample - loss: 0.2653 - accuracy: 0.9604
Epoch 675/1000
101/101 [==============================] - 0s 406us/sample - loss: 0.2650 - accuracy: 0.9604
Epoch 676/1000
101/101 [==============================] - 0s 544us/sample - loss: 0.2649 - accuracy: 0.9604
Epoch 677/1000
101/101 [==============================] - ETA: 0s - loss: 0.1551 - accuracy: 1.00 - 0s 734us/sample - loss: 0.2647 - accuracy: 0.9604
Epoch 678/1000
101/101 [==============================] - ETA: 0s - loss: 0.2437 - accuracy: 0.96 - 0s 683us/sample - loss: 0.2644 - accuracy: 0.9604
Epoch 679/1000
101/101 [==============================] - 0s 613us/sample - loss: 0.2641 - accuracy: 0.9604
Epoch 680/1000
101/101 [==============================] - 0s 475us/sample - loss: 0.2639 - accuracy: 0.9604
Epoch 681/1000
101/101 [============================

101/101 [==============================] - 0s 385us/sample - loss: 0.2483 - accuracy: 0.9604
Epoch 749/1000
101/101 [==============================] - 0s 415us/sample - loss: 0.2480 - accuracy: 0.9604
Epoch 750/1000
101/101 [==============================] - 0s 395us/sample - loss: 0.2478 - accuracy: 0.9604
Epoch 751/1000
101/101 [==============================] - 0s 415us/sample - loss: 0.2476 - accuracy: 0.9604
Epoch 752/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.2475 - accuracy: 0.9604
Epoch 753/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.2472 - accuracy: 0.9604
Epoch 754/1000
101/101 [==============================] - 0s 444us/sample - loss: 0.2470 - accuracy: 0.9604
Epoch 755/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.2467 - accuracy: 0.9604
Epoch 756/1000
101/101 [==============================] - 0s 464us/sample - loss: 0.2465 - accuracy: 0.9604
Epoch 757/1000
101/101 [===================

101/101 [==============================] - 0s 583us/sample - loss: 0.2327 - accuracy: 0.9604
Epoch 824/1000
101/101 [==============================] - 0s 425us/sample - loss: 0.2326 - accuracy: 0.9604
Epoch 825/1000
101/101 [==============================] - 0s 425us/sample - loss: 0.2323 - accuracy: 0.9604
Epoch 826/1000
101/101 [==============================] - 0s 434us/sample - loss: 0.2322 - accuracy: 0.9604
Epoch 827/1000
101/101 [==============================] - 0s 415us/sample - loss: 0.2321 - accuracy: 0.9604
Epoch 828/1000
101/101 [==============================] - 0s 681us/sample - loss: 0.2320 - accuracy: 0.9604
Epoch 829/1000
101/101 [==============================] - 0s 654us/sample - loss: 0.2317 - accuracy: 0.9604
Epoch 830/1000
101/101 [==============================] - 0s 721us/sample - loss: 0.2316 - accuracy: 0.9604
Epoch 831/1000
101/101 [==============================] - 0s 632us/sample - loss: 0.2313 - accuracy: 0.9604
Epoch 832/1000
101/101 [===================

101/101 [==============================] - 0s 415us/sample - loss: 0.2193 - accuracy: 0.9604
Epoch 899/1000
101/101 [==============================] - 0s 415us/sample - loss: 0.2192 - accuracy: 0.9604
Epoch 900/1000
101/101 [==============================] - 0s 365us/sample - loss: 0.2190 - accuracy: 0.9604
Epoch 901/1000
101/101 [==============================] - 0s 692us/sample - loss: 0.2189 - accuracy: 0.9604
Epoch 902/1000
101/101 [==============================] - 0s 592us/sample - loss: 0.2186 - accuracy: 0.9604
Epoch 903/1000
101/101 [==============================] - 0s 662us/sample - loss: 0.2184 - accuracy: 0.9604
Epoch 904/1000
101/101 [==============================] - 0s 592us/sample - loss: 0.2183 - accuracy: 0.9604
Epoch 905/1000
101/101 [==============================] - ETA: 0s - loss: 0.3014 - accuracy: 0.93 - 0s 751us/sample - loss: 0.2182 - accuracy: 0.9604
Epoch 906/1000
101/101 [==============================] - 0s 633us/sample - loss: 0.2180 - accuracy: 0.9604
E

101/101 [==============================] - 0s 391us/sample - loss: 0.2072 - accuracy: 0.9604
Epoch 974/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.2071 - accuracy: 0.9604
Epoch 975/1000
101/101 [==============================] - 0s 434us/sample - loss: 0.2069 - accuracy: 0.9604
Epoch 976/1000
101/101 [==============================] - 0s 484us/sample - loss: 0.2068 - accuracy: 0.9604
Epoch 977/1000
101/101 [==============================] - 0s 514us/sample - loss: 0.2067 - accuracy: 0.9604
Epoch 978/1000
101/101 [==============================] - 0s 474us/sample - loss: 0.2065 - accuracy: 0.9604
Epoch 979/1000
101/101 [==============================] - 0s 454us/sample - loss: 0.2063 - accuracy: 0.9604
Epoch 980/1000
101/101 [==============================] - 0s 405us/sample - loss: 0.2062 - accuracy: 0.9604
Epoch 981/1000
101/101 [==============================] - 0s 553us/sample - loss: 0.2062 - accuracy: 0.9604
Epoch 982/1000
101/101 [===================

In [12]:
# Single Test
# 예측되는 결과: 3
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]])
print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

[[1.6610142e-02 1.4089043e-02 5.4750632e-02 8.8586199e-01 1.1477941e-02
  2.0401023e-04 1.7006237e-02]] [3]


In [13]:
# x_data에 대하여 test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P